# Generated by Django 5.2.15 on 2026-06-15 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='taken_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='interpretation',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('exercise', 'Exercise')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('phq9', 'PHQ-9 (Depression)'), ('gad7', 'GAD-7 (Anxiety)')], default='phq9', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='severity',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately Severe'), ('severe', 'Severe')], default='minimal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
